config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :games
  resources :games
  devise_for :players
  get 'leaderboard/index'

  root 'leaderboard#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :player_a, :class_name => 'Player', :foreign_key => 'player_a_id'
  belongs_to :player_b, :class_name => 'Player', :foreign_key => 'player_b_id'
  validate :verify_scores
  after_create :set_winner

  def duration_format
    duration.strftime("%H:%M:%S")
  end

  def verify_scores
    if (self.score_player_a.to_i != self.score_player_b.to_i) && (self.score_player_a.to_i >= 21 || self.score_player_b.to_i >= 21)
      score_difference = self.score_player_a.to_i - self.score_player_b.to_i
      if (score_difference < 0)
        score_difference = score_difference * -1
      end
      if (score_difference < 2)
        errors.add(:game, 'Invalid game scores')
      end
    else 
      errors.add(:game, 'Invalid game scores')
    end
  end

  def set_winner
    if score_player_a > score_player_b
      self.player_a.update_attributes(wins: self.player_a.wins+1)
      self.player_b.update_attributes(losses: self.player_b.losses+1)
      winner = self.player_a
      loser = self.player_b
    else
      self.player_b.update_attributes(wins: self.player_b.wins+1)
      self.player_a.update_attributes(losses: self.player_a.losses+1)
      winner = self.player_b
      loser = self.player_a
    end
    set_global_score_points(winner, loser)
  end

  def set_global_score_points(winner, loser)
    if winner.global_score >= loser.global_score
      winner.update_attributes(global_score: winner.global_score+10)
    else
      winner.update_attributes(global_score: winner.global_score + loser.wins * 10)
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:player_a_id, :player_b_id, :duration, :score_player_a, :score_player_b)
    end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
    @players = Player.order(global_score: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= select("game", "player_a_id", Player.all.collect {|p| [ p.name, p.id ] })%><br>
  </div>
  <div class="field">
    <%= select("game", "player_b_id", Player.all.collect {|p| [ p.name, p.id ] })%><br>
  </div>
  <div class="field">
    <%= f.label :duration %> Hours:Minutes<br>
    <%= f.time_select :duration %>
  </div>
  <div class="field">
    <%= f.label :score_player_a %><br>
    <%= f.number_field :score_player_a %>
  </div>
  <div class="field">
    <%= f.label :score_player_b %><br>
    <%= f.number_field :score_player_b %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
 <div class="container">
  <h1>Editing Game</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @game %> |
  <%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<div class="container">  
  <p id="notice"><%= notice %></p>

  <h1>Listing Games</h1>

  <table  class="table table-hover">
    <thead>
      <tr>
        <th>Player A</th>
        <th>Player B</th>
        <th>Duration</th>
        <th>Score player a</th>
        <th>Score player b</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.player_a.name %></td>
          <td><%= game.player_b.name %></td>
          <td><%= game.duration_format %></td>
          <td><%= game.score_player_a %></td>
          <td><%= game.score_player_b %></td>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Game', new_game_path %>
</div>

app/views/games/new.html.erb
<div class="container">
  <h1>New Game</h1>

  <%= render 'form' %>

  <%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Player a:</strong>
    <%= @game.player_a.name %>
  </p>

  <p>
    <strong>Player b:</strong>
    <%= @game.player_b.name %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= @game.duration %>
  </p>

  <p>
    <strong>Score player a:</strong>
    <%= @game.score_player_a %>
  </p>

  <p>
    <strong>Score player b:</strong>
    <%= @game.score_player_b %>
  </p>

  <%= link_to 'Edit', edit_game_path(@game) %> |
  <%= link_to 'Back', games_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PingPong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Ping-pong board", root_path, {class: "navbar-brand"}%>
        
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Games", games_path %></li>
          <li><%= link_to "New Player", new_player_registration_path %></li>
          <li><%= link_to "New Game", new_game_path %></li>
          <li><%= link_to "Login", player_session_path %></li>
          <li><%= link_to "Log out", destroy_player_session_path, method: :delete %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>

app/views/leaderboard/index.html.erb
<div class="container">

  <!-- Main component for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Leader Board</h1>
    <table  class="table table-hover">
      <thead>
        <tr>
          <th>Player A</th>
          <th>Wins</th>
          <th>Losses</th>
          <th>Global Score</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @players.each do |player| %>
          <tr>
            <td><%= player.name %></td>
            <td><%= player.wins %></td>
            <td><%= player.losses %></td>
            <td><%= player.global_score %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>